const products=[
{name:'Nocturne',desc:'Пионы, розы, ранункулюсы',price:74,img:'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=900&q=85'},
{name:'Éclat',desc:'Розы, анемоны, эвкалипт',price:68,img:'https://images.unsplash.com/photo-1487070183336-b863922373d4?auto=format&fit=crop&w=900&q=85'},
{name:'Azure',desc:'Дельфиниум, белые розы, маттиола',price:72,img:'https://images.unsplash.com/photo-1508610048659-a06b669eaa5c?auto=format&fit=crop&w=900&q=85'},
{name:'Rosée',desc:'Садовые розы, ранункулюсы, астильба',price:65,img:'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=900&q=85'},
{name:'Soleil',desc:'Георгины, ромашки, жёлтые розы',price:59,img:'https://images.unsplash.com/photo-1494625927555-6ec4433b1571?auto=format&fit=crop&w=900&q=85'},
{name:'Velours',desc:'Бордовые розы, пионы, скабиоза',price:82,img:'https://images.unsplash.com/photo-1494336934272-f7d5a3f3f2e7?auto=format&fit=crop&w=900&q=85'},
{name:'Lilas',desc:'Сирень, дельфиниум, розы',price:69,img:'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=900&q=85'},
{name:'Jardin',desc:'Сезонные садовые цветы',price:76,img:'https://images.unsplash.com/photo-1495231916356-a86217efff12?auto=format&fit=crop&w=900&q=85'}];
const productsEl=document.getElementById('products'),cart=document.getElementById('cart'),overlay=document.getElementById('overlay'),cartItems=document.getElementById('cartItems'),cartTotal=document.getElementById('cartTotal'),cartCount=document.getElementById('cartCount'),toast=document.getElementById('toast');let basket=[];
productsEl.innerHTML=products.map((p,i)=>`<article class="product-card reveal" style="transition-delay:${i*45}ms"><div class="product-image"><img src="${p.img}" alt="${p.name}" loading="lazy"></div><div class="product-info"><div class="product-name">${p.name}</div><div class="product-desc">${p.desc}</div><div class="product-row"><span class="price">€${p.price}</span><button class="add" onclick="addToCart(${i})" aria-label="Добавить ${p.name}">+</button></div></div></article>`).join('');
function addToCart(index){const found=basket.find(x=>x.index===index);found?found.qty++:basket.push({index,qty:1});renderCart();openCart();showToast(`${products[index].name} добавлен в корзину`)}
function changeQty(index,delta){const item=basket.find(x=>x.index===index);if(!item)return;item.qty+=delta;if(item.qty<=0)basket=basket.filter(x=>x.index!==index);renderCart()}
function removeItem(index){basket=basket.filter(x=>x.index!==index);renderCart()}
function renderCart(){cartItems.innerHTML=basket.length?basket.map(item=>{const p=products[item.index];return `<div class="cart-item"><img src="${p.img}" alt=""><div><div class="cart-item-name">${p.name}</div><div class="cart-item-price">€${p.price}</div><div class="qty"><button onclick="changeQty(${item.index},-1)">−</button><span>${item.qty}</span><button onclick="changeQty(${item.index},1)">+</button></div></div><button class="remove" onclick="removeItem(${item.index})">×</button></div>`}).join(''):`<div style="opacity:.65;font-size:13px;padding-top:30px">В корзине пока ничего нет.</div>`;const count=basket.reduce((s,x)=>s+x.qty,0),total=basket.reduce((s,x)=>s+products[x.index].price*x.qty,0);cartCount.textContent=count;cartTotal.textContent=`€${total}`}
function openCart(){cart.classList.add('open');overlay.classList.add('active');document.body.classList.add('lock')}function closeCart(){cart.classList.remove('open');overlay.classList.remove('active');document.body.classList.remove('lock')}
document.getElementById('cartOpen').onclick=openCart;document.getElementById('cartClose').onclick=closeCart;overlay.onclick=closeCart;document.getElementById('checkout').onclick=()=>showToast(basket.length?'Демонстрационный заказ оформлен':'Сначала добавьте букет');document.getElementById('allProducts').onclick=()=>document.getElementById('collection').scrollIntoView({behavior:'smooth'});
document.getElementById('menuButton').onclick=()=>{const nav=document.querySelector('.nav');nav.classList.toggle('mobile-open');if(nav.classList.contains('mobile-open')){nav.style.display='flex';nav.style.position='fixed';nav.style.top='74px';nav.style.left='0';nav.style.right='0';nav.style.background='#35171d';nav.style.padding='25px';nav.style.flexDirection='column';nav.style.gap='22px'}else nav.removeAttribute('style')};
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1900)}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));renderCart();
